# Libraries

In [1]:
import pandas as pd

# Dataframes

In [2]:
# Import all files

file_path_1 = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\dim_diagnosis.csv'
dim_diagnosis = pd.read_csv(file_path_1)

file_path_2 = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\diabetic_data.csv'
diabetes = pd.read_csv(file_path_2)

file_path_3 = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\admission_type.csv'
adm_type = pd.read_csv(file_path_3)

file_path_4 =  r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\admission_source.csv'
adm_source = pd.read_csv(file_path_4)

file_path_5 = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\discharge_disposition.csv'
dis_disp = pd.read_csv(file_path_5)

# Create Dimensions and Fact

# Diagnosis

In [3]:
# Create a id for any value

dim_diagnosis.insert(
    0,
    'diagnosis_id',
    range(1,len(dim_diagnosis)+ 1)
)

In [4]:
dim_diagnosis.dtypes

diagnosis_id      int64
icd9_code        object
disease_name     object
short_name       object
disease_group    object
dtype: object

In [5]:
# dim_diagosis
diagnosis_lookup = (
    dim_diagnosis
    .set_index('icd9_code')['diagnosis_id']
    .to_dict()
)

# Medication

In [6]:
# Create a dimension for medications
medication_columns = [
    'metformin',
    'repaglinide',
    'nateglinide',
    'chlorpropamide',
    'glimepiride',
    'acetohexamide',
    'glipizide',
    'glyburide',
    'tolbutamide',
    'pioglitazone',
    'rosiglitazone',
    'acarbose',
    'miglitol',
    'troglitazone',
    'tolazamide',
    'examide',
    'citoglipton',
    'insulin',
    'glyburide-metformin',
    'glipizide-metformin',
    'glimepiride-pioglitazone',
    'metformin-rosiglitazone',
    'metformin-pioglitazone'
]

dim_medication = (
    diabetes[medication_columns]
    .drop_duplicates()
    .reset_index(drop=True)
)

In [7]:
dim_medication.insert(
    0,
    'medication_id',
    range(1, len(dim_medication)+ 1)
)

In [8]:
# dim_medication
medication_lookup = (
    dim_medication
    .set_index(medication_columns)['medication_id']
    .to_dict()
)

In [9]:
# Rename columns for SQL Server
dim_medication= dim_medication.rename(columns={
    'metformin': 'metformin_status',
    'repaglinide': 'repaglinide_status',
    'nateglinide': 'nateglinide_status',
    'chlorpropamide': 'chlorpropamide_status',
    'glimepiride': 'glimepiride_status',
    'acetohexamide': 'acetohexamide_status',
    'glipizide': 'glipizide_status',
    'glyburide': 'glyburide_status',
    'tolbutamide': 'tolbutamide_status',
    'pioglitazone': 'pioglitazone_status',
    'rosiglitazone': 'rosiglitazone_status',
    'acarbose': 'acarbose_status',
    'miglitol': 'miglitol_status',
    'troglitazone': 'troglitazone_status',
    'tolazamide': 'tolazamide_status',
    'examide': 'examide_status',
    'citoglipton': 'citoglipton_status',
    'insulin': 'insulin_status',
    'glyburide-metformin': 'glyburide_metformin_status',
    'glipizide-metformin': 'glipizide_metformin_status',
    'glimepiride-pioglitazone': 'glimepiride_pioglitazone_status',
    'metformin-rosiglitazone': 'metformin_rosiglitazone_status',
    'metformin-pioglitazone': 'metformin_pioglitazone_status'
})

In [10]:
dim_medication

,medication_id,metformin_status,repaglinide_status,nateglinide_status,chlorpropamide_status,glimepiride_status,acetohexamide_status,glipizide_status,glyburide_status,tolbutamide_status,...,troglitazone_status,tolazamide_status,examide_status,citoglipton_status,insulin_status,glyburide_metformin_status,glipizide_metformin_status,glimepiride_pioglitazone_status,metformin_rosiglitazone_status,metformin_pioglitazone_status
0,1,No,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
1,2,No,No,No,No,No,No,No,No,No,...,No,No,No,No,Up,No,No,No,No,No
2,3,No,No,No,No,No,No,Steady,No,No,...,No,No,No,No,No,No,No,No,No,No
3,4,No,No,No,No,No,No,Steady,No,No,...,No,No,No,No,Steady,No,No,No,No,No
4,5,No,No,No,No,No,No,No,No,No,...,No,No,No,No,Steady,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,1262,Steady,Down,No,No,No,No,No,No,No,...,No,No,No,No,Up,No,No,No,No,No
1262,1263,No,Up,No,No,No,No,Steady,No,No,...,No,No,No,No,Down,No,No,No,No,No
1263,1264,No,No,No,No,No,No,Steady,No,No,...,No,No,No,No,Steady,No,No,No,No,No
1264,1265,Steady,No,No,No,Steady,No,Down,Steady,No,...,No,No,No,No,No,No,No,No,No,No
1265,1266,No,No,Down,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No

In [11]:
medication_status_columns = [
    'metformin_status',
    'repaglinide_status',
    'nateglinide_status',
    'chlorpropamide_status',
    'glimepiride_status',
    'acetohexamide_status',
    'glipizide_status',
    'glyburide_status',
    'tolbutamide_status',
    'pioglitazone_status',
    'rosiglitazone_status',
    'acarbose_status',
    'miglitol_status',
    'troglitazone_status',
    'tolazamide_status',
    'examide_status',
    'citoglipton_status',
    'insulin_status',
    'glyburide_metformin_status',
    'glipizide_metformin_status',
    'glimepiride_pioglitazone_status',
    'metformin_rosiglitazone_status',
    'metformin_pioglitazone_status'
]

In [12]:
dim_medication.columns

Index(['medication_id', 'metformin_status', 'repaglinide_status',
       'nateglinide_status', 'chlorpropamide_status', 'glimepiride_status',
       'acetohexamide_status', 'glipizide_status', 'glyburide_status',
       'tolbutamide_status', 'pioglitazone_status', 'rosiglitazone_status',
       'acarbose_status', 'miglitol_status', 'troglitazone_status',
       'tolazamide_status', 'examide_status', 'citoglipton_status',
       'insulin_status', 'glyburide_metformin_status',
       'glipizide_metformin_status', 'glimepiride_pioglitazone_status',
       'metformin_rosiglitazone_status', 'metformin_pioglitazone_status'],
      dtype='object')

In [13]:
# Temp dataframe
medication_merge = diabetes.merge(
    dim_medication,
    left_on=medication_columns,
    right_on=medication_status_columns,
    how='left'
)

# Readmission

In [14]:
dim_readmission = (
    diabetes[['readmitted']]
    .drop_duplicates()
    .sort_values('readmitted')
    .reset_index(drop=True)
)

dim_readmission.insert(
    0,
    'readmission_id',
    range(1, len(dim_readmission) + 1)
)

dim_readmission

   readmission_id readmitted
0               1        <30
1               2        >30
2               3         NO

In [15]:
readmission_lookup = (
    dim_readmission
    .set_index('readmitted')['readmission_id']
    .to_dict()
)

# Admission Type

In [16]:
dim_admission_type = adm_type.copy()
dim_admission_type

   admission_type_id admission_type_description
0                  1                  Emergency
1                  2                     Urgent
2                  3                   Elective
3                  4                    Newborn
4                  5              Not Available
5                  7              Trauma Center
6                  8                 Not Mapped

# Admission Source

In [17]:
dim_admission_source = adm_source.copy()
dim_admission_source

    admission_source_id                       admission_source_description
0                     1                                 Physician Referral
1                     2                                    Clinic Referral
2                     3                                       HMO Referral
3                     4                           Transfer from a hospital
4                     5     Transfer from a Skilled Nursing Facility (SNF)
5                     6         Transfer from another health care facility
6                     7                                     Emergency Room
7                     8                              Court/Law Enforcement
8                     9                                      Not Available
9                    10              Transfer from critial access hospital
10                   11                                    Normal Delivery
11                   12                                 Premature Delivery
12                   13                                          Sick Baby
13                   14                                   Extramural Birth
14                   15                                      Not Available
15                   18           Transfer From Another Home Health Agency
16                   19             Readmission to Same Home Health Agency
17                   20                                         Not Mapped
18                   21                                    Unknown/Invalid
19                   22   Transfer from hospital inpt/same fac reslt in...
20                   23                          Born inside this hospital
21                   24                         Born outside this hospital
22                   25            Transfer from Ambulatory Surgery Center
23                   26                              Transfer from Hospice

# Discharge Disposition

In [18]:
dim_discharge_disposition = dis_disp.copy()
dim_discharge_disposition

,discharge_disposition_id,discharge_disposition_description
0,1,Discharged to home
1,2,Discharged/transferred to another short term h...
2,3,Discharged/transferred to SNF
3,4,Discharged/transferred to ICF
4,5,Discharged/transferred to another type of inpa...
5,6,Discharged/transferred to home with home healt...
6,7,Left AMA
7,8,Discharged/transferred to home under care of H...
8,9,Admitted as an inpatient to this hospital
9,10,Neonate discharged to another hospital for neo...
10,11,Expired
11,12,Still patient or expected to return for outpat...
12,13,Hospice / home
13,14,Hospice / medical facility
14,15,Discharged/transferred within this institution...
15,16,Discharged/transferred/referred another instit...
16,17,Discharged/transferred/referred to this instit...
17,19,"Expired at home. Medicaid only, hospice."
18,20,"Expired in a medical facility. Medicaid only, ..."
19,21,"Expired, place unknown. Medicaid only, hospice."
20,22,Discharged/transferred to another rehab fac in...
21,23,Discharged/transferred to a long term care hos...
22,24,Discharged/transferred to a nursing facility c...
23,25,Not Mapped
24,26,Unknown/Invalid
25,30,Discharged/transferred to another Type of Heal...
26,27,Discharged/transferred to a federal health car...
27,28,Discharged/transferred/referred to a psychiatr...
28,29,Discharged/transferred to a Critical Access Ho...

# Fact

In [19]:
fact_hospitalization = diabetes[
    [
        'encounter_id',
        'patient_nbr',
        'admission_type_id',
        'admission_source_id',
        'discharge_disposition_id',
        'age',
        'gender',
        'diabetesMed',
        'change',
        'A1Cresult',
        'max_glu_serum',
        'time_in_hospital',
        'num_medications',
        'number_emergency',
        'number_inpatient',
        'number_outpatient'
    ]
].copy()

In [20]:
fact_hospitalization = fact_hospitalization.rename(columns={
    'diabetesMed' : 'diabetes_med',
    'change' : 'medication_changed',
    'A1Cresult' : 'a1c_result'
})

In [21]:
fact_hospitalization['diagnosis_id'] = (
    diabetes['diag_1'].map(diagnosis_lookup)
)

In [22]:
fact_hospitalization['readmission_id'] = (
    diabetes['readmitted']
    .map(readmission_lookup)
)

In [23]:
fact_hospitalization['medication_id'] = medication_merge['medication_id']
fact_hospitalization

,encounter_id,patient_nbr,admission_type_id,admission_source_id,discharge_disposition_id,age,gender,diabetes_med,medication_changed,a1c_result,max_glu_serum,time_in_hospital,num_medications,number_emergency,number_inpatient,number_outpatient,diagnosis_id,readmission_id,medication_id
0,2278392,8222157,6,1,25,[0-10),Female,No,No,NaN,NaN,1,1,0,0,0,126,3,1
1,149190,55629189,1,7,1,[10-20),Female,Yes,Ch,NaN,NaN,3,18,0,0,0,145,2,2
2,64410,86047875,1,7,1,[20-30),Female,Yes,No,NaN,NaN,2,13,0,1,2,456,3,3
3,500364,82442376,1,7,1,[30-40),Male,Yes,Ch,NaN,NaN,2,16,0,0,0,556,3,2
4,16680,42519267,1,7,1,[40-50),Male,Yes,Ch,NaN,NaN,1,8,0,0,0,56,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,1,7,3,[70-80),Male,Yes,Ch,>8,NaN,3,16,0,0,0,104,2,18
101762,443847782,74694222,1,5,4,[80-90),Female,Yes,No,NaN,NaN,5,18,0,1,0,383,3,5
101763,443854148,41088789,1,7,1,[70-80),Male,Yes,Ch,NaN,NaN,1,9,0,0,1,238,3,18
101764,443857166,31693671,2,7,3,[80-90),Female,Yes,Ch,NaN,NaN,10,21,0,1,0,695,3,507
101765,443867222,175429310,1,7,1,[70-80),Male,No,No,NaN,NaN,6,3,0,0,0,362,3,1

In [36]:
# organize columns from SQL Server

fact_hospitalization = fact_hospitalization[
    [
        'encounter_id',
        'patient_nbr',
        'admission_type_id',
        'admission_source_id',
        'discharge_disposition_id',
        'diagnosis_id',
        'medication_id',
        'readmission_id',
        'age',
        'gender',
        'diabetes_med',
        'medication_changed',
        'a1c_result',
        'max_glu_serum',
        'time_in_hospital',
        'num_medications',
        'number_emergency',
        'number_inpatient',
        'number_outpatient'
    ]
]

In [ ]:
# convert to BIT values

 fact_hospitalization["diabetes_med"] = (
    fact_hospitalization["diabetes_med"]
    .map({
        "Yes": 1,
        "No": 0
    })
    .astype("int8")
) 

fact_hospitalization["medication_changed"] = (
    fact_hospitalization["medication_changed"]
    .map({
        "Ch": 1,
        "No": 0
    })
    .astype("int8")
)

#Validations

---

# Matching test

### Test line 150 Diagnosis

In [25]:
print(diabetes.loc[150, 'diag_1'])
print(fact_hospitalization.loc[150, 'diagnosis_id'])

414
265

In [26]:
dim_diagnosis.loc[
    dim_diagnosis['diagnosis_id'] == fact_hospitalization.loc[150, 'diagnosis_id']
]

,diagnosis_id,icd9_code,disease_name,short_name,disease_group
264,265,414,Other forms of chronic ischemic heart disease,Chr ischemic hrt dis NOS,Circulatory System

### Test line 374 Diagnosis

In [27]:
print(diabetes.loc[374, 'diag_1'])
print(fact_hospitalization.loc[374, 'diagnosis_id'])

486
327

In [28]:
dim_diagnosis.loc[
    dim_diagnosis['diagnosis_id'] == fact_hospitalization.loc[374, 'diagnosis_id']
]

,diagnosis_id,icd9_code,disease_name,short_name,disease_group
326,327,486,"Pneumonia, organism unspecified","Pneumonia, organism NOS",Respiratory System

### Left JOIN Diagnosis Test

In [29]:
# Check if all diag_1 have a matching
validation_diag = (
    fact_hospitalization[['diagnosis_id']]
    .merge(
        dim_diagnosis[['diagnosis_id', 'icd9_code']],
        on='diagnosis_id',
        how='left'
    )
)

(diabetes['diag_1'] == validation_diag['icd9_code']).all()

np.True_

### Readmission Test

In [30]:
fact_hospitalization["readmission_id"].isna().sum()

np.int64(0)

In [31]:
validation_readmission = (
    fact_hospitalization[['readmission_id']]
    .merge(
        dim_readmission[['readmission_id', 'readmitted']],
        on='readmission_id',
        how='left'
    )
)
(diabetes['readmitted'] == validation_readmission['readmitted']).all()

np.True_

### Medication Test

In [32]:
fact_hospitalization['medication_id'].isna().sum()

np.int64(0)

In [33]:
validation_meddication = (
    fact_hospitalization[['medication_id']]
    .merge(
        dim_medication,
        on='medication_id',
        how='left'
    )
)

compare = (
    diabetes[medication_columns].reset_index(drop=True)
    ==
    validation_meddication[medication_status_columns]
        .rename(columns=dict(zip(medication_status_columns, medication_columns)))
        .reset_index(drop=True)
)

compare.all().all()

np.True_

### Validation before export

In [34]:
print(dim_diagnosis.shape)
print(dim_medication.shape)
print(dim_readmission.shape)
print(dim_admission_type.shape)
print(dim_admission_source.shape)
print(dim_discharge_disposition.shape)
print(fact_hospitalization.shape)
print(fact_hospitalization.info())

(717, 5)
(1266, 24)
(3, 2)
(7, 2)
(24, 2)
(29, 2)
(101766, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   admission_type_id         101766 non-null  int64
 3   admission_source_id       101766 non-null  int64
 4   discharge_disposition_id  101766 non-null  int64
 5   age                       101766 non-null  object
 6   gender                    101766 non-null  object
 7   diabetes_med              101766 non-null  object
 8   medication_changed        101766 non-null  object
 9   a1c_result                17018 non-null   object
 10  max_glu_serum             5346 non-null    object
 11  time_in_hospital          101766 non-null  int64
 12  num_medications           101766 non-null  int64
 13  number_emergency          101766 non-null  int64
 14  number_inpatient          101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  diagnosis_id              101766 non-null  int64
 17  readmission_id            101766 non-null  int64
 18  medication_id             101766 non-null  int64
dtypes: int64(13), object(6)
memory usage: 14.8+ MB
None

# Export CSV files

In [39]:
output_path = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\Dim_&_Fact'

In [ ]:
output_path = r'C:\Users\henry\Desktop\Projects\Diabetes_130_US\Dataset\Dim_&_Fact'

dim_diagnosis.to_csv(
    f'{output_path}\\dim_diagnosis.csv',
    index=False,
    encoding='utf-8-sig'
)

dim_readmission.to_csv(
    f'{output_path}\\dim_readmission.csv',
    index=False,
    encoding='utf-8-sig'
)

dim_admission_type.to_csv(
    f'{output_path}\\dim_admission_type.csv',
    index=False,
    encoding='utf-8-sig'
)

dim_admission_source.to_csv(
    f'{output_path}\\dim_admission_source.csv',
    index=False,
    encoding='utf-8-sig'
)

dim_discharge_disposition.to_csv(
    f'{output_path}\\dim_discharge_disposition.csv',
    index=False,
    encoding='utf-8-sig'
)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 18-19: truncated \UXXXXXXXX escape (1153242342.py, line 1)

In [37]:
# Remove columns in dim medication

dim_medication.drop(
    columns=[
        'examide_status',
        'citoglipton_status'
    ],
    inplace=True
)

In [ ]:
dim_medication.to_csv(
    f'{output_path}\\dim_medication.csv',
    index=False,
    encoding='utf-8-sig'
)

In [44]:
fact_hospitalization['a1c_result'] = (
    fact_hospitalization['a1c_result']
    .fillna('None')
)

fact_hospitalization['max_glu_serum'] = (
    fact_hospitalization['max_glu_serum']
    .fillna('None')
)

fact_hospitalization.to_csv(
    f'{output_path}\\fact_hospitalization.csv',
    index=False,
    encoding='utf-8-sig'
)